CREATE TABLE company_table (
    company_id STRING NOT NULL,
    company_name STRING NOT NULL,
    addr1 STRING,
    addr2 STRING,
    city STRING,
    state STRING,
    country STRING,
    zip STRING,
    salesperson STRING,
    phone STRING,
    extension STRING,
    fax STRING,
    email STRING,
    web_addr STRING,
    tax_id STRING,
    resale STRING,
    status STRING,
    customer INT64,
    vendor INT64,
    other INT64,
    notes STRING,
    PRIMARY KEY (company_id)
);

CREATE TABLE component_table (
    component_id INT64 NOT NULL OPTIONS(description="Auto-generated component ID"),
    customer_id STRING,
    component_type STRING,
    title STRING,
    oem_pn STRING,
    component_description STRING,
    size STRING,
    supplier_brand_id STRING,
    color STRING,
    notes STRING,
    uom STRING,
    component_status STRING,
    owned_by INT64,
    packaging_component INT64,
    PRIMARY KEY (component_id),
    FOREIGN KEY (customer_id) REFERENCES `your_project_id.your_dataset_id.company_table` (company_id) ON DELETE CASCADE
);

CREATE TABLE contact_table (
    contact_id INT64 NOT NULL OPTIONS(description="Auto-generated contact ID"),
    company_id STRING NOT NULL,
    company_name STRING,
    fname STRING,
    lname STRING,
    contact_type STRING,
    title STRING,
    dept STRING,
    add_1 STRING,
    add_2 STRING,
    city STRING,
    state_in_country STRING,
    zip STRING,
    country STRING,
    phone STRING,
    extension STRING,
    cell_phone_number STRING,
    third_party_company STRING,
    fax STRING,
    email STRING,
    notes STRING,
    PRIMARY KEY (contact_id)
);

CREATE TABLE product_table (
    product_id INT64 NOT NULL OPTIONS(description="Auto-generated product ID"),
    old_abs_id STRING,
    customer_id STRING NOT NULL,
    product_category STRING,
    oem_product_id STRING,
    product_title STRING,
    product_desc STRING,
    product_repl STRING,
    master_format STRING,
    master_received DATE,
    master_label STRING,
    master_capacity STRING,
    master_loc STRING,
    films_loc STRING,
    date_code_required INT64,
    date_code_position STRING,
    inner_hub STRING,
    inner_hub_position STRING,
    floodcoat INT64,
    rimage_print INT64,
    num_colors INT64,
    color_1 STRING,
    color_2 STRING,
    color_3 STRING,
    color_4 STRING,
    color_5 STRING,
    color_6 STRING,
    color_7 STRING,
    color_8 STRING,
    color_notes STRING,
    component_1 STRING,
    component_2 STRING,
    component_3 STRING,
    component_4 STRING,
    component_5 STRING,
    component_6 STRING,
    component_7 STRING,
    component_8 STRING,
    component_9 STRING,
    component_10 STRING,
    component_11 STRING,
    component_12 STRING,
    component_name1 STRING,
    component_name2 STRING,
    component_name3 STRING,
    component_name4 STRING,
    component_name5 STRING,
    component_name6 STRING,
    component_name7 STRING,
    component_name8 STRING,
    component_name9 STRING,
    component_name10 STRING,
    component_name11 STRING,
    component_name12 STRING,
    component_type1 STRING,
    component_type2 STRING,
    component_type3 STRING,
    component_type4 STRING,
    component_type5 STRING,
    component_type6 STRING,
    component_type7 STRING,
    component_type8 STRING,
    component_type9 STRING,
    component_type10 STRING,
    component_type11 STRING,
    component_type12 STRING,
    packaging_notes STRING,
    product_notes STRING,
    product_status STRING,
    PRIMARY KEY (product_id),
    FOREIGN KEY (customer_id) REFERENCES `your_project_id.your_dataset_id.company_table` (company_id) ON DELETE CASCADE
);

CREATE TABLE location_table (
    id INT64 NOT NULL OPTIONS(description="Auto-generated ID"),
    location_id STRING NOT NULL,
    location_type STRING,
    item_id INT64,
    qty INT64 DEFAULT 0,
    item_owner STRING,
    physical_location STRING,
    notes STRING,
    PRIMARY KEY (id),
    INDEX (location_id)
);

CREATE TABLE location_history (
    id INT64 NOT NULL OPTIONS(description="Auto-generated ID"),
    location_id STRING NOT NULL,
    item_id INT64 NOT NULL DEFAULT 0,
    qty INT64 NOT NULL DEFAULT 0,
    date_added DATE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE item_check_in_table (
    id INT64 NOT NULL OPTIONS(description="Auto-generated ID"),
    customer_id STRING,
    item_id INT64,
    mfr_pn STRING,
    description STRING,
    carrier STRING,
    quantity STRING,
    disposition STRING,
    signed_for_by STRING,
    date_in DATETIME,
    date_complete DATETIME,
    PRIMARY KEY (id)
);

CREATE TABLE order_table (
    order_id INT64 NOT NULL OPTIONS(description="Auto-generated ID"),
    company_id STRING NOT NULL,
    company_name STRING,
    product_id INT64 NOT NULL,
    product_name STRING,
    product_type STRING,
    salesperson STRING,
    requestor STRING,
    customer_contact STRING,
    re_order BOOL,
    factory_order_quantity INT64,
    custom_invoice BOOL,
    custom_packing_slip BOOL,
    custom_quantity INT64,
    custom_unit_price FLOAT64,
    custom_total_price FLOAT64,
    non_inventory_line_item1 STRING,
    non_inventory_invoice1 BOOL,
    non_inventory_packing_slip1 BOOL,
    non_inventory_quantity1 INT64,
    non_inventory_unit_price1 FLOAT64,
    non_inventory_total_price1 FLOAT64,
    non_inventory_line_item2 STRING,
    non_inventory_invoice2 BOOL,
    non_inventory_packing_slip2 BOOL,
    non_inventory_quantity2 INT64,
    non_inventory_unit_price2 FLOAT64,
    non_inventory_total_price2 FLOAT64,
    non_inventory_line_item3 STRING,
    non_inventory_invoice3 BOOL,
    non_inventory_packing_slip3 BOOL,
    non_inventory_quantity3 INT64,
    non_inventory_unit_price3 FLOAT64,
    non_inventory_total_price3 FLOAT64,
    non_inventory_line_item4 STRING,
    non_inventory_invoice4 BOOL,
    non_inventory_packing_slip4 BOOL,
    non_inventory_quantity4 INT64,
    non_inventory_unit_price4 FLOAT64,
    non_inventory_total_price4 FLOAT64,
    non_inventory_line_item5 STRING,
    non_inventory_invoice5 BOOL,
    non_inventory_packing_slip5 BOOL,
    non_inventory_quantity5 INT64,
    non_inventory_unit_price5 FLOAT64,
    non_inventory_total_price5 FLOAT64,
    non_inventory_line_item6 STRING,
    non_inventory_invoice6 BOOL,
    non_inventory_packing_slip6 BOOL,
    non_inventory_quantity6 INT64,
    non_inventory_unit_price6 FLOAT64,
    non_inventory_total_price6 FLOAT64,
    inventory_item1 STRING,
    inventory_item1_name STRING,
    inventory_item1_type STRING,
    inventory_invoice1 BOOL,
    inventory_packing_slip1 BOOL,
    inventory_quantity1 INT64,
    inventory_unit_price1 FLOAT64,
    inventory_total_price1 FLOAT64,
    inventory_item2 STRING,
    inventory_item2_name STRING,
    inventory_item2_type STRING,
    inventory_invoice2 BOOL,
    inventory_packing_slip2 BOOL,
    inventory_quantity2 INT64,
    inventory_unit_price2 FLOAT64,
    inventory_total_price2 FLOAT64,
    inventory_item3 STRING,
    inventory_item3_name STRING,
    inventory_item3_type STRING,
    inventory_invoice3 BOOL,
    inventory_packing_slip3 BOOL,
    inventory_quantity3 INT64,
    inventory_unit_price3 FLOAT64,
    inventory_total_price3 FLOAT64,
    assembly_charges_quantity INT64,
    assembly_charges_unit_price FLOAT64,
    assembly_charges_total_price FLOAT64,
    date_code_printing_charges_quantity INT64,
    date_code_printing_charges_unit_price FLOAT64,
    date_code_printing_charges_total_price FLOAT64,
    date_code_setup_charge FLOAT64,
    number_of_screens INT64,
    art_manipulation FLOAT64,
    sub_total FLOAT64,
    tax_rate FLOAT64,
    tax FLOAT64,
    freight_charges FLOAT64,
    order_price_total FLOAT64,
    invoice_date STRING,
    invoice_date_paid STRING,
    invoice_notes STRING,
    abs_sales_order_date STRING,
    customer_order_date STRING,
    customer_po_date STRING,
    customer_po_number INT64,
    credit_checked BOOL DEFAULT NULL,
    days_turn INT DEFAULT NULL,
    date_code_printing VARCHAR(50) DEFAULT NULL,
    customer_provided_material TEXT,
    customer_material_eta VARCHAR(50) DEFAULT NULL,
    customer_notes TEXT DEFAULT NULL,
    vendor_notes TEXT DEFAULT NULL,
    order_notes TEXT DEFAULT NULL,
    order_status VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (order_id)
);
