create schema 191_database; /* schema for entire DB */

create table contact_table (
  contact_id mediumint NOT NULL auto_increment,
  customer_id varchar(8) NOT NULL default '',
  company varchar(128) NOT NULL default '',
  fname varchar(64) default NULL,
  lname varchar(64) default NULL,
  contact_type varchar(64) default NULL,
  title varchar(64) default NULL,
  dept varchar(128) default NULL,
  add_1 varchar(64) default NULL,
  add_2 varchar(64) default NULL,
  city varchar(64) default NULL,
  state_in_country varchar(4) default NULL,
  zip varchar(16) default NULL,
  country varchar(128) default NULL,
  phone varchar(15) default NULL,
  extension varchar(5) default NULL,
  cell_phone_number varchar(15) default NULL,
  third_party_company varchar(128) default '',
  fax varchar(15) default NULL,
  email varchar(128) default NULL,
  notes mediumtext,
  PRIMARY KEY  (contact_id)
  #PRIMARY KEY  (contact_id),
  #FOREIGN KEY (company) REFERENCES company_table(company_name)
);

create table location_table(
	location_id INT PRIMARY KEY NOT NULL,
	location_type TEXT,
	item_id INT FOREIGN KEY REFERENCES item_check_in_table(item_id),
	qty INT,
	item_owner TEXT,
	physical_location TEXT,
	notes TEXT
);

create table item_check_in_table(
	item_id INT PRIMARY KEY NOT NULL,
	customer_id INT FOREIGN KEY REFERENCES contact_table(customer_id),
	mfr_pn TEXT,
	item_description TEXT,
	carrier TEXT,
	quantity INT,
	disposition TEXT,
	signed_by_for TEXT,
	date_in DATETIME;
	date_completed DATE
);

create table component_table (
	customer_id TEXT PRIMARY KEY NOT NULL,
	component_type TEXT,
	oem_pn INT,
	description_1 TEXT,
	description_2 TEXT,
	description_3 TEXT,
	description_4 TEXT,
	description_5 TEXT,
	size TEXT,
	supplier_brand_id TEXT,
	color TEXT,
	notes TEXT,
	owned_by TEXT,
	uom TEXT,
	component_status TEXT,
	packaging_component BIT,
	item_location TEXT,
);

create table product_table(
	product_pn INT PRIMARY KEY NOT NULL, 
	old_pn INT, 
	customer_name TEXT,
	customer_id INT, 
	product_category TEXT,
	oem_pn INT, 
	product_title TEXT, 
	product_desc TEXT, 
	replication TEXT, 
	master_format TEXT, 
	master_received DATE, 
	master_label TEXT, 
	master_capacity TEXT, 
	master_location TEXT, 
	date_code_req BIT, 
	date_code_position TEXT, 
	inner_hub TEXT, 
	inner_hub_position TEXT, 
	flood_coat BIT, 
	rimage_print BIT, 
	color TEXT,
	color_notes TEXT, 
	component TEXT, 
	packaging_notes TEXT, 
	product_notes TEXT, 
	product_status TEXT,
	location_id INT, 
);

create table order_table (
	-- Billing Information (Company's Information)
    company_name TEXT,
    contact TEXT,
    phone INT,
    address1 TEXT,
    address2 TEXT,
    city TEXT,
    state TEXT,
    zip INT,
    -- Product Information
	product_id INT PRIMARY KEY NOT NULL,
    product_category TEXT,
    OEM_product_id INT,
    product_title TEXT,
    number_of_colors INT,
    salesperson TEXT,
    requestor TEXT,
    customer_contact TEXT,
    re_order BIT,
    -- Custom Product
    product_title TEXT,
    product_id INT,
    factory_order_quantity INT,
    custom_invoice BIT,
    custom_packing_slip BIT,
    custom_quantity INT,
    custom_unit_price FLOAT,
    custom_total_price FLOAT,
    -- Non-Inventory Line Items
    non_inventory_line_item TEXT,
    non_inventory_invoice BIT,
    non_inventory_packing_slip BIT,
    non_inventory_quantity INT,
    non_inventory_unit_price FLOAT,
    non_inventory_total_price FLOAT,
    -- Inventory Items
    inventory_item TEXT,
    inventory_invoice BIT,
    inventory_packing_slip BIT,
    inventory_quantity INT,
    inventory_unit_price FLOAT,
    inventory_total_price FLOAT,
    -- Billing Information
    assembly_charges_quantity INT,
    assembly_charges_unit_price FLOAT,
    assembly_charges_total_price FLOAT,
    date_code_printing_charges_quantity INT,
    date_code_printing_charges1_unit_price FLOAT,
    date_code_printing_charges2_total_price FLOAT,
    date_code_setup_charge FLOAT,
    number_of_screens INT,
    art_manipulation FLOAT,
    sub_total FLOAT,
    taxable BIT,
    tax_rate FLOAT,
    tax FLOAT,
    freight_charges FLOAT,
    order_price_total FLOAT,
    -- Invoice Information
    invoice_date DATE,
    invoice_date_paid DATE,
    invoice_notes TEXT,
    abs_sales_order_date DATE,
    customer_order_date DATE,
    customer_po_date DATE,
    customer_po_number INT,
    credit_checked BIT,
    days_turn INT,
    date_code_printing DATE,
    assembly_by TEXT,
    disc_manufactured_by TEXT,
    cd_dvd_brand TEXT,
    disc_provided_by TEXT,
    customer_provided_material TEXT,
    customer_material_eta DATE,
    customer_notes TEXT,
    vendor_notes TEXT,
    order_notes TEXT,
    order_status TEXT
);

create table shipping_table(
	customer_id INT PRIMARY KEY NOT NULL,
	company_name TEXT,
	contact_name TEXT, 
	add1 TEXT,
	add2 TEXT,
	city TEXT,
	country_state TEXT,
	zip INT,
	province TEXT,
	country TEXT,
	phone TEXT,
	fax TEXT,
);

create table shipment_info_table{
	fedex TEXT,
	ups TEXT,
	courier_willcall TEXT,
	other_ship_method TEXT,
	payment_type TEXT,
	account_number TEXT,
	request_ship_date DATE,
	request_ship_time DATETIME,
	arrival_ship_date DATE,
	arrival_ship_time DATETIME,
	fob TEXT,
	notes TEXT
}

create table company_table{
	company_ID INT PRIMARY KEY NOT NULL,
	company_Name TEXT,
	tax_ID INT,
	status TEXT,
	customer BIT,
	OEM BIT,
	credit_checked BIT,
	vendor BIT,
	salesperson TEXT,
	phone INT,
	extension INT,
	fax TEXT,
	email TEXT,
	web_addr TEXT,
	country TEXT,
	state TEXT,
	zip INT,
	city TEXT,
	Addr1 TEXT,
	Addr2 TEXT
}